# Copyright (C) 2026 ShinKouyo <i@0x0f.dev>
# SPDX-License-Identifier: AGPL-3.0-or-later

table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;

    ct state invalid drop
    ct state { established, related } accept

    iif lo accept
    iif != lo ip daddr 127.0.0.1/8 drop
    iif != lo ip6 daddr ::1/128 drop

    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept

    tcp dport 22604 accept

    reject with icmpx type port-unreachable
  }

  chain forward {
    type filter hook forward priority 0; policy drop;
  }

  chain output {
    type filter hook output priority 0; policy accept;
  }
}
