# Copyright (C) 2026 ShinKouyo <i@0x0f.dev>
# SPDX-License-Identifier: AGPL-3.0-or-later

include fonts.conf
include cursor.conf
include scrollback.conf
include mouse.conf
include performance.conf
include bell.conf
include window.conf
include tab-bar.conf
include colors.conf
include advanced.conf
include os.conf
include keys.conf
